---
#==============================================================================================
# Global Configuration
#==============================================================================================
- name:                        Define global settings
  hosts:                       localhost
  connection:                  local
  gather_facts:                no

  vars_files:
     - ./global-vars/apic-details.yaml

  tasks:
    - name:                    apic details
      set_fact:
        apic_info:             &apic_info
          host:                "{{ apic_info.host }}"
          username:            "{{ apic_info.username }}"
          password:            "{{ apic_info.password }}"
          validate_certs:      no

        rest_info:             &rest_info
          use_proxy:           no
          path:                /api/mo/.json
          method:              post
  tags:                        always
