---
#==============================================================================================
# Global Configuration
#==============================================================================================
- name:                   Define global settings
  hosts:                  localhost
  connection:             local
  gather_facts:           no

  vars_files:
     - ../../../global-vars/apic-dave.yaml

# Call configuration state from -e "@../../../global-vars/create.yaml"
# or
# Call configuration state from -e "@../../../global-vars/delete.yaml"
  tasks:
    - name:
      set_fact:
        desired_state:    #present
        desired_status:   #modified,created

    - name:               apic details
      set_fact:
        apic_info:        &apic_info
          host:           "{{ apic_info.host }}"
          username:       "{{ apic_info.username }}"
          password:       "{{ apic_info.password }}"
          validate_certs: no

        rest_info:        &rest_info
          use_proxy:      no
          path:           /api/mo/.json
          method:         post
  tags:                   always

#==============================================================================================
# Begin Plays
#
# Available Tags:
#               snapshot
#               filters
#               contract
#               subject
#               aci_contract_subject_to_filter
#               bind-contract
#==============================================================================================
- import_playbook:        ../../../snapshot-local.yaml
  vars:
    snapshotDescription:  Prior-to-Mango-Production-Contracts
  tags:                   snapshot

#==============================================================================================
# Create filters in the common tenant
#==============================================================================================
- import_playbook:        ../../common/contracts/filter-builder.yaml
  tags:                   filters

#==============================================================================================
# Add the contracts
#==============================================================================================
# naming structure:                   consumer tenant|app|epg to provider tenant|app|epg
- name:                               Configure contracts between epgs
  hosts:                              localhost
  connection:                         local
  gather_facts:                       no

  vars_files:
     - ./vars/contract-vars.yaml

  tasks:
    - name:                           Add a new contract
      aci_contract:
        <<:                           *apic_info
        tenant:                       "{{ item.cons_tn_name }}"
        contract:                     "{{ item.cont_name }}"
        description:                  "{{ item.description }}"
        scope:                        "{{ item.scope }}"
        state:                        "{{ desired_state }}"
      with_items:
        "{{ contract }}"
      loop_control:
        pause: 1
      tags:                           contract

    - name:                           Add a new contract subject
      aci_contract_subject:
        <<:                           *apic_info
        tenant:                       "{{ item.cons_tn_name }}"
        contract:                     "{{ item.cont_name }}"
        subject:                      "{{ item.subject }}"
        description:                  ""
        reverse_filter:               yes
#        priority:                    ""
#        dscp:                        ""
        state:                        "{{ desired_state }}"
      with_items:
        "{{ contract }}"
      loop_control:
        pause: 1
      tags:                           subject

    - name:                           Add a new contract subject to filter binding
      aci_contract_subject_to_filter:
        <<:                           *apic_info
        tenant:                       "{{ item.cons_tn_name }}"
        contract:                     "{{ item.cont_name }}"
        subject:                      "{{ item.subject }}"
        filter:                       "{{ item.subject }}_src_port_{{ item.src_port }}_to_dst_port_{{ item.dst_port }}"
  #      log:                         none
        state:                        "{{ desired_state }}"
      with_items:
        "{{ contract }}"
      loop_control:
        pause: 1
      tags:                           subject-to-filter

#==============================================================================================
# Bind the contracts
#==============================================================================================
# naming structure:                   consumer tenant|app|epg to provider tenant|app|epg
- name:                               Configure contracts between tenants
  hosts:                              localhost
  connection:                         local
  gather_facts:                       no

  vars_files:
     - ./vars/contract-vars.yaml

  tasks:
    - name:                           Bind Contract to Consumer EPG
      aci_epg_to_contract:
        <<:                           *apic_info
        tenant:                       "{{ item.cons_tn_name }}"
        ap:                           "{{ item.cons_ap_name }}"
        epg:                          "{{ item.cons_epg_name }}"
        contract:                     "{{ item.cont_name }}"
        contract_type:                consumer
        state:                        "{{ desired_state }}"
      with_items:
        "{{ contract }}"
      loop_control:
        pause: 1

    - name:                           Bind Contract to Provider EPG
      aci_epg_to_contract:
        <<:                           *apic_info
        tenant:                       "{{ item.prov_tn_name }}"
        ap:                           "{{ item.prov_ap_name }}"
        epg:                          "{{ item.prov_epg_name }}"
        contract:                     "{{ item.cont_name }}"
        contract_type:                provider
        state:                        "{{ desired_state }}"
      with_items:
        "{{ contract }}"
      loop_control:
        pause: 1
  tags:                               bind-contract
