#==============================================================================================
# Application Profiles.
#==============================================================================================
ap:
- tenant:         "ctf"
  app_profile:    "10.193.x.x"

#==============================================================================================
# EPGs.
#==============================================================================================
epg:
- tenant:         "ctf"
  app_profile:    "10.193.x.x"
  bd:             "10.193.x.x"
  epg:            "windows-servers"

#==============================================================================================
# Domains.
#==============================================================================================
domain:
- tenant:         "ctf"
  app_profile:    "10.193.x.x"
  epg:            "windows-servers"
  domain_name:    "physical_servers"
  domain_type:    "phys"

#==============================================================================================
# Bindings.
#==============================================================================================
static_binding:
- tenant:         "ctf"
  app_profile:    "10.193.x.x"
  epg:            "windows-servers"
  interface_type: "switch_port"
  leafs:          "101"
  path:           "1/11"
  vlan:           "2000"

- tenant:         "ctf"
  app_profile:    "10.193.x.x"
  epg:            "windows-servers"
  interface_type: "switch_port"
  leafs:          "102"
  path:           "1/11"
  vlan:           "2000"
