---
#==============================================================================================
# Global Configuration
#==============================================================================================
- name:                   Define global settings
  hosts:                  localhost
  connection:             local
  gather_facts:           no

  vars_files:
     - ../../../global-vars/apic-details.yaml

  tasks:
    - name:
      set_fact:
        desired_state:    present
        #desired_state:   absent
        #desired_status:  modified,created
        #desired_status:  deleted

    - name:               apic details
      set_fact:
        apic_info:        &apic_info
          host:           "{{ apic_info.host }}"
          username:       "{{ apic_info.username }}"
          password:       "{{ apic_info.password }}"
          validate_certs: no

        rest_info:        &rest_info
          use_proxy:      no
          path:           /api/mo/.json
          method:         post
  tags:                   always

#==============================================================================================
# Begin Plays
#
# Available Tags:
#               snapshot
#               filters
#==============================================================================================
- import_playbook:        ../../../snapshot-local.yaml
  vars:
    snapshotDescription:  Prior-to-configuring-Common-Tenant-Filters
  tags:                   snapshot

#==============================================================================================
# Configure filters
#==============================================================================================
- name:                              Configure filters
  hosts:                             localhost
  connection:                        local
  gather_facts:                      no

  tasks:
    - name:                          Read variable files
      include_vars:
          name:                      filters
          dir:                       ./vars
          ignore_unknown_extensions: True
          extensions:
            - yaml

    - name:                          Create/Delete Filters
      aci_filter:
        <<:                          *apic_info
        tenant:                      "common"
        filter:                      "{{ item.subject }}_src_port_{{ item.src_port }}_to_dst_port_{{ item.dst_port }}"
        state:                       "{{ desired_state }}"
      with_items:
        - "{{ filters.tcp }}"
        - "{{ filters.udp }}"
      loop_control:
        pause: 1

# Create a new filter entry
    - name:                          Create/Delete Filter Entries
      aci_filter_entry:
        <<:                          *apic_info
        filter:                      "{{ item.subject }}_src_port_{{ item.src_port }}_to_dst_port_{{ item.dst_port }}"
        entry:                       "src_port_{{ item.src_port }}_to_dst_port_{{ item.dst_port }}"
        tenant:                      "common"
        ether_type:                  "ip"
        ip_protocol:                 "{{ item.subject }}"
        dst_port:                    "{{ item.dst_port }}"
        state:                       "{{ desired_state }}"
# Comment in/out filters as required
      with_items:
        - "{{ filters.tcp }}"
        - "{{ filters.udp }}"
      loop_control:
        pause: 1
  tags: filters
