---
#==============================================================================================
# Global Configuration
#==============================================================================================
- name:                   Define global settings
  hosts:                  localhost
  connection:             local
  gather_facts:           no

  vars_files:
     - ../../../global-vars/apic-details.yaml

  tasks:
    - name:
      set_fact:
        desired_state:    present
        #desired_state:   absent
        #desired_status:  modified,created
        #desired_status:  deleted

    - name:               apic details
      set_fact:
        apic_info:        &apic_info
          host:           "{{ apic_info.host }}"
          username:       "{{ apic_info.username }}"
          password:       "{{ apic_info.password }}"
          validate_certs: no

        rest_info:        &rest_info
          use_proxy:      no
          path:           /api/mo/.json
          method:         post
  tags:                   always

#==============================================================================================
# Begin Plays
#
# Available Tags:
#               snapshot
#               ap
#               epg
#               domain
#               static_binding
#==============================================================================================
- import_playbook:        ../../../snapshot.yaml
  vars:
    snapshotDescription:  Prior-to-configuring-Windows-APs-in-the-ctf-tenant
  tags:                   snapshot

#==============================================================================================
# Create Application Profile
#==============================================================================================
- name:                          Create Application Profiles, EPG and Bindings
  hosts:                         localhost
  connection:                    local
  gather_facts:                  no

  vars_files:
     - ./vars/windows-servers-vars.yaml

  tasks:
    - name:                      Create Application Profile
      aci_ap:
        <<:                      *apic_info
        tenant:                  "{{ item.tenant }}"
        ap:                      "{{ item.app_profile }}"
        description:
        state:                   "{{ desired_state }}"
      with_items:
        - "{{ ap }}"
      loop_control:
        pause: 1
      tags:
        - ap


    - name:                      Create EPG
      aci_epg:
        <<:                      *apic_info
        tenant:                  "{{ item.tenant }}"
        ap:                      "{{ item.app_profile }}"
        bd:                      "{{ item.bd }}"
        epg:                     "{{ item.epg }}"
        description:
        state:                   "{{ desired_state }}"
      with_items:
        - "{{ epg }}"
      loop_control:
        pause: 1
      tags:
        - epg


    - name:                      Add domain to an EPG
      aci_epg_to_domain:
        <<:                      *apic_info
        tenant:                  "{{ item.tenant }}"
        ap:                      "{{ item.app_profile }}"
        epg:                     "{{ item.epg }}"
        domain:                  "{{ item.domain_name }}"
        domain_type:             "{{ item.domain_type }}"
        state:                   "{{ desired_state }}"
      with_items:
        - "{{ domain }}"
      loop_control:
        pause: 1
      tags:
        - domain


    - name:                      Deploy Static Path binding for given EPG
      aci_static_binding_to_epg:
        <<:                      *apic_info
        tenant:                  "{{ item.tenant }}"
        ap:                      "{{ item.app_profile }}"
        epg:                     "{{ item.epg }}"
        encap_id:                "{{ item.vlan }}"
        deploy_immediacy:        immediate
        interface_mode:          trunk
        interface_type:          "{{ item.interface_type }}"
        pod_id:                  1
        leafs:                   "{{ item.leafs }}"
        interface:               "{{ item.path }}"
        state:                   "{{ desired_state }}"
      with_items:
        - "{{ static_binding }}"
      loop_control:
        pause: 1
      tags:
        - static_binding
