---
#==============================================================================================
# Global Configuration
#==============================================================================================
- name:                       Define global settings
  hosts:                      localhost
  connection:                 local
  gather_facts:               no

  vars_files:
     - ../../../global-vars/apic-details.yaml

# Call configuration state from -e "@../../../global-vars/create.yaml"
# or
# Call configuration state from -e "@../../../global-vars/delete.yaml"
  tasks:
    - name:
      set_fact:
        desired_state:        #present
        desired_status:       #modified,created

    - name:                   apic details
      set_fact:
        apic_info:            &apic_info
          host:               "{{ apic_info.host }}"
          username:           "{{ apic_info.username }}"
          password:           "{{ apic_info.password }}"
          validate_certs:     no

        rest_info:            &rest_info
          use_proxy:          no
          path:               /api/mo/.json
          method:             post
  tags:                       always

#==============================================================================================
# Begin Plays
#
# Available Tags:
#               snapshot
#               bridge-domains
#               gateways
#==============================================================================================
- import_playbook:            ../../../snapshot-local.yaml
  vars:
    snapshotDescription:      Prior-to-configuring-Common-Tenant-Bridge-Domains-and-Gateways
  tags:                       snapshot

#==============================================================================================
# Create Bridge Domains
#==============================================================================================
- name:                       Configure Bridge Domains
  hosts:                      localhost
  connection:                 local
  gather_facts:               no

  vars_files:
     - ./vars/bridge-domain-vars.yaml

  tasks:
    - name:                   Create/Delete Bridge Domain
      aci_bd:
        <<:                   *apic_info
        tenant:               "{{ item.tenant }}"
        vrf:                  "{{ item.vrf }}"
        bd:                   "{{ item.bd }}"
        description:          "{{ item.descr }}"
        state:                "{{ desired_state }}"
      with_items:
        - "{{ bd }}"
      loop_control:
        pause:                1
  tags:
    - bridge-domains

#==============================================================================================
# Add gateways to Bridge Domains
#==============================================================================================
- name:                       Configure Gateways
  hosts:                      localhost
  connection:                 local
  gather_facts:               no

  vars_files:
     - ./vars/bridge-domain-vars.yaml

  tasks:
    - name:                   Create/Delete Bridge Domains
      aci_bd_subnet:
        <<:                   *apic_info
        tenant:               "{{ item.tenant }}"
        bd:                   "{{ item.bd }}"
        gateway:              "{{ item.gw }}"
        mask:                 "{{ item.mask }}"
        scope:                "{{ item.scope }}"
        state:                "{{ desired_state }}"
      with_items:
        - "{{ gw }}"
      loop_control:
        pause:                1
  tags:
    - gateways

#==============================================================================================
# Add L3Out to Bridge Domains
#==============================================================================================
- name:                   Configure Gateways
  hosts:                  localhost
  connection:             local
  gather_facts:           no

  vars_files:
    - ./vars/bridge-domain-vars.yaml

  tasks:
    - name:               Create/Delete L3out mapping to BD
      aci_bd_to_l3out:
        <<:               *apic_info
        tenant:           "{{ item.tenant }}"
        bd:               "{{ item.bd }}"
        l3out:            "{{ item.l3out }}"
        state:            "{{ desired_state }}"
      with_items:
        - "{{ l3out }}"
      loop_control:
        pause:            1
  tags:
    - l3out
